# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 427d8e5012c1d3a6518322787d3c9709640d2ac3546903e7161ab575257bcec8be1deca4ed0d3b0548ac85919f3f427296be90f9d9cd854bb491969c55e21154

test:
  secret_key_base: ed5716df21e44c873b3f0e142e7305cbe63e325801db8b3323e42770cd481e8827cab59ccd9331ed48d2081702339b126c9a5897f4e045bb6fb13c531a53726c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
